---
title: "AdvTutorial"
author: "Nicholas Gawron & Livia Popa"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(rnoaa)
library(forecast)
install.packages("xts")                      # Install & load xts package
library("xts")
```

# Advanced Tutorial


## Importing Data From NCEI

Text on importing **with an API**.

```{r}
library(httr)
library(jsonlite)
base_url <- "https://www.ncdc.noaa.gov/cdo-web/api/v2/"
endpoint <- "datasets"
token <- "gykUMKPJzpcpQonBrUWjbFqYevOPkhwc"
full_url <- paste0(base_url, "/",endpoint,"/")
Raw  <- GET(full_url)

curl -H "token:gykUMKPJzpcpQonBrUWjbFqYevOPkhwc" "https://www.ncdc.noaa.gov/cdo-web/api/v2/datasets" $.ajax({ url:https://www.ncdc.noaa.gov/cdo-web/api/v2/datasets, data:{/datasets}, headers:{ token:gykUMKPJzpcpQonBrUWjbFqYevOPkhwc} })
```

## Machine Learning 

### Basic Plotting with Ggplot 

EDA is how we can motivate future ML models!

Text on *plotting*. 

### Content from beg. lecture

```{r}

cardinal <- read_csv("cardinal_data.csv", 
     col_types = list(`Average Air Temperature (F)` = col_number(), 
         `Maximum Air Temperature (F)` = col_number(), 
         `Minimum Air Temperature (F)` = col_number(), 
         `Average Experimental Leaf Wetness (mV)` = col_number(), 
         `Total Precipitation (in)` = col_number(), 
         `Average Relative Humidity (%)` = col_number(), 
         `Average Soil Moisture (m3/m3)` = col_number(), 
         `Average Soil Temperature (F)` = col_number(), 
         `Average Solar Radiation (W/m2)` = col_number(), 
         `Average Station Pressure (mb)` = col_number()))

cardinal<-drop_na(cardinal)
str(cardinal)
cardinal$Date<-as.Date(cardinal$Date, tryFormats= c("%m/%d/%y"))
view(cardinal)

#changes col names
colnames(cardinal)=c("date","AvgT","MaxT","MinT","AvgLw","Tprep","AvgHum","AvgSm","AvgSt","AvgSr","AvgStp")



cardinal$IfRain<- (cardinal$Tprep>0)
cardinal$IfRain<-as.factor(as.integer(cardinal$IfRain))


```

### Logistic Regression ! TIme Series forecasting

```{r}


```
```{r}

```

